app = 'insurancebot'
primary_region = 'waw'

[build]
    dockerfile = "Dockerfile"

[env]
    ASPNETCORE_URLS = "http://+:8080"
    ASPNETCORE_ENVIRONMENT = "Production"

[http_service]
    internal_port = 8080
    force_https = true
    auto_stop_machines = false
    auto_start_machines = true
    min_machines_running = 0
    processes = ['app']

[[vm]]
    memory = '1gb'
    cpu_kind = 'shared'
    cpus = 1